- .gitlab-ci.py
- CHANGELOG.md
- gcip/addons/kaniko/jobs.py
- gcip/addons/python/jobs.py
@dvonessen again a set of separate commits
> commit batch

- .github/ISSUE_TEMPLATE/Bug.md
- .github/ISSUE_TEMPLATE/Feature.md
- .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
Added Bug.md, Feature.md, PULL_REQUEST_TEMPLATE.md templates.
They are inspired from https://github.com/restic/restic.
No!
Checklist
---------
> Bug, Feature and Pull request templates:

- .gitignore
- CHANGELOG.md
- tests/conftest.py
- tests/unit/comparison_files/test_readme_cache_jobs_test.yml
- tests/unit/test_cache.py
- tests/unit/test_readme_cache_jobs.py
* Added gitlab_ci_environment_variables monkeypatch fixture. It allows patching environment variables.
* Added gitlab_ci_environmnet_variables fixture to tests.
No
Checklist
---------
> Added new fixture to allow patching of os environment variable.

- .gitlab-ci.py
- gcip/addons/kaniko/jobs.py
- gcip/core/variables.py
- gitlabci-local.sh
- tests/conftest.py
- tests/unit/comparison_files/test_docker_test_default_docker_jobs.yml
- tests/unit/comparison_files/test_kaniko_test_default_kaniko_job.yml
- tests/unit/test_docker.py
- tests/unit/test_kaniko.py
* add script to run gitlab ci pipeline locally
* added missing pytests
* do yapf formatting and isort
no
Checklist
---------
> Gitlabci local

- CHANGELOG.md
- docs/user/index.adoc
- gcip/__init__.py
- gcip/core/cache.py
- gcip/core/job.py
- gcip/core/pipeline.py
- gcip/core/sequence.py
- tests/unit/test_readme_missing_namespace.py
> finished api documentation of gcip.core.job

- CHANGELOG.md
- docs/user/index.adoc
- gcip/__init__.py
- gcip/core/cache.py
- gcip/core/job.py
- gcip/core/pipeline.py
- gcip/core/sequence.py
- tests/unit/test_readme_missing_namespace.py
simply resolved remaining mypy issues
> resolved all mypy issues

- CHANGELOG.md
- gcip/addons/container/__init__.py
- gcip/addons/container/images.py
- gcip/addons/container/jobs/dive.py
- gcip/addons/container/jobs/kaniko.py
- gcip/addons/python/jobs.py
Added a new class which is used as a container for predefined images. 
Those images can be used within gcip but also in all jobs if wished.
Checklist
---------
> Add predefined container images

- CHANGELOG.md
- tests/conftest.py
> Improve conftest check orig

- CHANGELOG.md
- gcip/addons/container/jobs/crane.py
- tests/unit/comparison_files/test_addons_container_crane_test_advanced_crane_job.yml
- tests/unit/comparison_files/test_addons_container_crane_test_default_crane_job.yml
- tests/unit/test_addons_container_crane.py
Added new addon to gcip to too get a job which copies container images between registries.
No
Checklist
---------
> Added crane addon

- .vscode/settings.json
- CHANGELOG.md
- gcip/addons/container/images.py
- gcip/addons/container/jobs/trivy.py
- tests/unit/comparison_files/test_addons_container_jobs_trivy_test_trivy_advanced_scan_local_image.yml
- tests/unit/comparison_files/test_addons_container_jobs_trivy_test_trivy_simple_scan_local_image.yml
- tests/unit/test_addons_container_jobs_trivy.py
Added new addon to container library to allow scanning container images of vulnerabilities.
None 
Checklist
---------
> Added trivy addon.

- CHANGELOG.md
- gcip/addons/container/config.py
- tests/unit/comparison_files/test_addons_container_config_test_complex_docker_client_config.yml
- tests/unit/comparison_files/test_addons_container_config_test_docker_client_config.yml
- tests/unit/comparison_files/test_addons_container_crane_test_advanced_crane_copy_job.yml
- tests/unit/comparison_files/test_addons_container_crane_test_advanced_crane_push_job.yml
> Normalize config_file_path.

- .gitlab-ci.py
- .gitlab-ci.yml
- CHANGELOG.md
- gcip/addons/container/jobs/trivy.py
- gitlabci-local.sh
- setup.cfg
This PR fixes some issues with the linter. 
See https://gitlab.com/thomassteinbach/gitlab-ci-python-library/-/jobs/1161953981
None
Checklist
---------
> Fix linter

- .gitlab-ci.py
- CHANGELOG.md
- gcip/addons/container/config.py
- gcip/addons/container/jobs/kaniko.py
- gcip/addons/container/registries.py
- tests/unit/comparison_files/test_addons_container_config_test_complex_docker_client_config.yml
- tests/unit/comparison_files/test_addons_container_config_test_docker_client_config.yml
- tests/unit/comparison_files/test_addons_container_config_test_docker_client_config_registry_constant.yml
- tests/unit/comparison_files/test_addons_container_config_test_docker_client_config_set_config_file_path.yml
- tests/unit/comparison_files/test_addons_container_kaniko_test_container_kaniko_job_docker_v2_replacement_.yml
- tests/unit/comparison_files/test_addons_container_kaniko_test_default_kaniko_job.yml
- tests/unit/comparison_files/test_addons_container_kaniko_test_simple_kaniko_job.yml
- tests/unit/test_addons_container_config.py
- tests/unit/test_addons_container_kaniko.py
- tests/unit/test_addons_container_registries.py
Removed custom docker client config from kaniko job.
Added DockerClientConfig as a optional client configuration to kaniko job.
Simplyfied function and sorted initialisation tests an actuall composing of job.
Checklist
---------
> Added new kaniko structure

- .gitignore
- .vscode/settings.json
- CHANGELOG.md
- gcip/core/sequence.py
- requirements.txt
- mainly add documentation to gcip.core.sequence.Sequence
- added some missing methods to initialize and override artifacts_paths to gcip.core.sequence.Sequence
- configured code coverage reports in vsc
Checklist
---------
> Documentation

- .devcontainer/devcontainer.json
- .gitignore
- README.md
Adds a .devcontainer configuration for VS Code. 
Checklist
---------
> Devcontainer config

- CHANGELOG.md
- gcip/addons/container/images.py
Fixed wrong docker tag for crane container.
Checklist
---------
> Fixed wrong docker tag for crane container.

- tests/unit/comparison_files/test_addons_container_crane_test_advanced_crane_copy_job.yml
- tests/unit/comparison_files/test_addons_container_crane_test_simple_crane_copy_job.yml
- tests/unit/comparison_files/test_addons_container_crane_test_simple_crane_push_job.yml
- tests/unit/comparison_files/test_addons_container_sequences_build_test_addons_container_sequences_build_scan_push_image.yml
- tests/unit/comparison_files/test_addons_container_sequences_build_test_build_scan_push_image.yml
Fixed missing update of comparision_files
Checklist
---------
> Fixed missing test update.

- CHANGELOG.md
- README.md
- gcip/core/variables.py
* Added documentation to the `gcip.core.variables` module.
Checklist
---------
> extended documentation of the variables module

- CHANGELOG.md
- README.md
- gcip/core/include.py
- gcip/core/job.py
- gcip/core/variables.py
* Added full API documentation of the `gcip.core.include` module.
Checklist
---------
> Added full API documentation of the  module.

- CHANGELOG.md
- README.md
- gcip/core/image.py
- gcip/core/include.py
- gcip/core/job.py
- gcip/core/variables.py
Added full documentation to the image class.
Checklist
---------
> added full api doc to the image class

- CHANGELOG.md
- README.md
- gcip/core/image.py
- gcip/core/include.py
- gcip/core/job.py
- gcip/core/pipeline.py
- gcip/core/service.py
- gcip/core/variables.py
* Add full API documentation to the gcip.core.pipeline.Pipeline class
* Removed an unwanted method from the Pipeline class
Checklist
---------
> added full api doc to the pipeline class

- CHANGELOG.md
- gcip/addons/python/job_scripts.py
- gcip/core/job.py
- tests/conftest.py
- tests/unit/comparison_files/test_job_test_job_render.yml
- tests/unit/comparison_files/test_python_full_stack_test.yml
- tests/unit/comparison_files/test_python_full_stack_test_with_mypy.yml
- tests/unit/test_job.py
Added job tests
Adding public properties to Job class.
Checklist
---------
> Added @properties for all object variables.

- CHANGELOG.md
- gcip/addons/aws/__init__.py
- gcip/addons/aws/helper.py
- gcip/addons/container/registries.py
- gcip/core/artifact.py
- requirements.txt
- tests/unit/test_addons_aws_helper.py
- tests/unit/test_addons_container_registries.py
Adds to `gcip.addons.container.registries.Registry` the AWS staticmethod to allow getting ECR registry urls.
Checklist
---------
> Add aws registry method

- CHANGELOG.md
- gcip/addons/security/__init__.py
- gcip/addons/security/sops.py
- tests/unit/test_addons_security_sops.py
Added sops_export_decrypted_values function to sops module.
Added new gcip.addons.security.sops module.
Checklist
---------
> Added new gcip.addons.security.sops module.

- CHANGELOG.md
- gcip/core/service.py
Added documentation to the service module.
Checklist
---------
> Docs service
